import { Inter , Roboto} from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ClinicInfo from "./components/ClinicInfo";
import FloatingMenu from "./components/FloatingMenu";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({
  weight: ['300','400','500','700','900'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: {
    default:'Dr. Gopal Raval - Best Pulmonologist in Ahmedabad | Critical Care Specialist | Sleep Disorder Specialist'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="file.png" type="image/x-icon" />
        <meta name="google-site-verification" content="nsMAE5RKUSH77fwDU9-vp9R8CcT-99TWHyDGtB0KQ3g" />
      </head>
      <body className={roboto.className}>
        <Header/>
        <ClinicInfo/>
        <FloatingMenu/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
